INSERT INTO barangays (name, official_display_name) VALUES
('Bagsangan', 'Barangay Bagsangan'),
('Bacolod', 'Barangay Bacolod (Poblacion)'),
('Batang', 'Barangay Batang'),
('Bolos', 'Barangay Bolos'),
('Buenavista', 'Barangay Buenavista'),
('Bulawan', 'Barangay Bulawan'),
('Carriedo', 'Barangay Carriedo'),
('Casini', 'Barangay Casini'),
('Cawayan', 'Barangay Cawayan'),
('Cogon', 'Barangay Cogon'),
('Gabao', 'Barangay Gabao'),
('Gulang-Gulang', 'Barangay Gulang-Gulang'),
('Gumapia', 'Barangay Gumapia'),
('Liang', 'Barangay Liang'),
('Macawayan', 'Barangay Macawayan'),
('Mapaso', 'Barangay Mapaso'),
('Monbon', 'Barangay Monbon'),
('Patag', 'Barangay Patag'),
('Salvacion', 'Barangay Salvacion'),
('San Agustin', 'Barangay San Agustin (Poblacion)'),
('San Isidro', 'Barangay San Isidro (Palogtok)'),
('San Juan', 'Barangay San Juan (Poblacion)'),
('San Julian', 'Barangay San Julian (Poblacion)'),
('San Pedro', 'Barangay San Pedro (Poblacion)'),
('Santo Domingo', 'Barangay Santo Domingo (Lamboon)'),
('Tabon-Tabon', 'Barangay Tabon-Tabon'),
('Tinampo', 'Barangay Tinampo'),
('Tongdol', 'Barangay Tongdol');