INSERT INTO barangays (name, official_display_name) VALUES
('Bacolod', 'Barangay Bacolod'),
('Bagsac', 'Barangay Bagsac'),
('Batang', 'Barangay Batang'),
('Bolos', 'Barangay Bolos'),
('Buenavista', 'Barangay Buenavista'),
('Bulawan', 'Barangay Bulawan'),
('Carriedo', 'Barangay Carriedo'),
('Casini', 'Barangay Casini'),
('Cawayan', 'Barangay Cawayan'),
('Cogon', 'Barangay Cogon'),
('Gabao', 'Barangay Gabao'),
('Gulang-Gulang', 'Barangay Gulang-Gulang'),
('Gumapia', 'Barangay Gumapia'),
('Iligan', 'Barangay Iligan'),
('Liang', 'Barangay Liang'),
('Macawayan', 'Barangay Macawayan'),
('Mapaso', 'Barangay Mapaso'),
('Monbon', 'Barangay Monbon'),
('Patag', 'Barangay Patag'),
('Salvacion', 'Barangay Salvacion'),
('San Agustin', 'Barangay San Agustin'),
('San Isidro', 'Barangay San Isidro'),
('San Julian', 'Barangay San Julian'),
('San Pedro', 'Barangay San Pedro'),
('Santo Niño', 'Barangay Santo Niño'),
('Tabon-Tabon', 'Barangay Tabon-Tabon'),
('Tinampo', 'Barangay Tinampo'),
('Tulay', 'Barangay Tulay');\n