-- supabase/migrations/002_enums.sql

CREATE TYPE incident_type AS ENUM (
  'THEFT',
  'PHYSICAL_INJURY',
  'THREATS',
  'TRESPASSING',
  'MALICIOUS_MISCHIEF',
  'SLANDER',
  'DOMESTIC_VIOLENCE',
  'PROPERTY_DISPUTE',
  'OTHER'
);

CREATE TYPE case_status AS ENUM (
  'DRAFT',
  'FILED',
  'UNDER_REVIEW',
  'ACTIVE',
  'REFERRED',
  'RESOLVED',
  'CLOSED',
  'ARCHIVED'
);

CREATE TYPE transfer_status AS ENUM (
  'PENDING',
  'VERIFIED',
  'REJECTED',
  'COMPLETED'
);

CREATE TYPE audit_action AS ENUM (
  'CREATE',
  'UPDATE',
  'DELETE',
  'ARCHIVE',
  'RESTORE',
  'TRANSFER',
  'MERGE',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',
  'LOGOUT',
  'PASSWORD_CHANGE',
  'PASSWORD_RESET',
  'RECOVERY_REQUEST',
  'RECOVERY_APPROVAL',
  'ACCOUNT_ACTIVATION',
  'ACCOUNT_DEACTIVATION',
  'REPORT_GENERATION',
  'PDF_EXPORT',
  'EXCEL_EXPORT',
  'CSV_EXPORT',
  'VIEW_SENSITIVE',
  'DOWNLOAD_ATTACHMENT',
  'AUTHORIZATION_FAILURE'
);
